/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Swap: {
      address: "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner_",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "DtToFil",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "success",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "FilToDt",
          inputs: [],
          outputs: [
            {
              name: "sucess",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setErc404",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "fil",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "dog",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {
        owner: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        renounceOwnership: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        transferOwnership: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
      },
    },
    Dogtoken: {
      address: "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "name_",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol_",
              type: "string",
              internalType: "string",
            },
            {
              name: "decimals_",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "maxTotalSupplyERC721_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "initialOwner_",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "DOMAIN_SEPARATOR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ID_ENCODING_PREFIX",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender_",
              type: "address",
              internalType: "address",
            },
            {
              name: "valueOrId_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc20Approve",
          inputs: [
            {
              name: "spender_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "erc20BalanceOf",
          inputs: [
            {
              name: "owner_",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc20TotalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc20TransferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "erc721Approve",
          inputs: [
            {
              name: "spender_",
              type: "address",
              internalType: "address",
            },
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "erc721BalanceOf",
          inputs: [
            {
              name: "owner_",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc721TotalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc721TransferExempt",
          inputs: [
            {
              name: "target_",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc721TransferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getApproved",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getERC721QueueLength",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getERC721TokensInQueue",
          inputs: [
            {
              name: "start_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "count_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isApprovedForAll",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "minted",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nonces",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owned",
          inputs: [
            {
              name: "owner_",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerOf",
          inputs: [
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "erc721Owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "permit",
          inputs: [
            {
              name: "owner_",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deadline_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "v_",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "r_",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "s_",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data_",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setApprovalForAll",
          inputs: [
            {
              name: "operator_",
              type: "address",
              internalType: "address",
            },
            {
              name: "approved_",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setERC721TransferExempt",
          inputs: [
            {
              name: "account_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSelfERC721TransferExempt",
          inputs: [
            {
              name: "state_",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenURI",
          inputs: [
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "valueOrId_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "units",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "updatedtokenURI",
          inputs: [
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "path",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "success",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ApprovalForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyExists",
          inputs: [],
        },
        {
          type: "error",
          name: "DecimalsTooLow",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientAllowance",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidApproval",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidExemption",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidOperator",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidRecipient",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSender",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSigner",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSpender",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidTokenId",
          inputs: [],
        },
        {
          type: "error",
          name: "MintLimitReached",
          inputs: [],
        },
        {
          type: "error",
          name: "NotFound",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnedIndexOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "PermitDeadlineExpired",
          inputs: [],
        },
        {
          type: "error",
          name: "QueueEmpty",
          inputs: [],
        },
        {
          type: "error",
          name: "QueueFull",
          inputs: [],
        },
        {
          type: "error",
          name: "QueueOutOfBounds",
          inputs: [],
        },
        {
          type: "error",
          name: "RecipientIsERC721TransferExempt",
          inputs: [],
        },
        {
          type: "error",
          name: "Unauthorized",
          inputs: [],
        },
        {
          type: "error",
          name: "UnsafeRecipient",
          inputs: [],
        },
      ],
      inheritedFunctions: {
        owner: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        renounceOwnership: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        transferOwnership: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        DOMAIN_SEPARATOR: "lib/erc404/contracts/ERC404.sol",
        ID_ENCODING_PREFIX: "lib/erc404/contracts/ERC404.sol",
        allowance: "lib/erc404/contracts/ERC404.sol",
        approve: "lib/erc404/contracts/ERC404.sol",
        balanceOf: "lib/erc404/contracts/ERC404.sol",
        decimals: "lib/erc404/contracts/ERC404.sol",
        erc20Approve: "lib/erc404/contracts/ERC404.sol",
        erc20BalanceOf: "lib/erc404/contracts/ERC404.sol",
        erc20TotalSupply: "lib/erc404/contracts/ERC404.sol",
        erc20TransferFrom: "lib/erc404/contracts/ERC404.sol",
        erc721Approve: "lib/erc404/contracts/ERC404.sol",
        erc721BalanceOf: "lib/erc404/contracts/ERC404.sol",
        erc721TotalSupply: "lib/erc404/contracts/ERC404.sol",
        erc721TransferExempt: "lib/erc404/contracts/ERC404.sol",
        erc721TransferFrom: "lib/erc404/contracts/ERC404.sol",
        getApproved: "lib/erc404/contracts/ERC404.sol",
        getERC721QueueLength: "lib/erc404/contracts/ERC404.sol",
        getERC721TokensInQueue: "lib/erc404/contracts/ERC404.sol",
        isApprovedForAll: "lib/erc404/contracts/ERC404.sol",
        minted: "lib/erc404/contracts/ERC404.sol",
        name: "lib/erc404/contracts/ERC404.sol",
        nonces: "lib/erc404/contracts/ERC404.sol",
        owned: "lib/erc404/contracts/ERC404.sol",
        ownerOf: "lib/erc404/contracts/ERC404.sol",
        permit: "lib/erc404/contracts/ERC404.sol",
        safeTransferFrom: "lib/erc404/contracts/ERC404.sol",
        setApprovalForAll: "lib/erc404/contracts/ERC404.sol",
        setSelfERC721TransferExempt: "lib/erc404/contracts/ERC404.sol",
        supportsInterface: "lib/erc404/contracts/ERC404.sol",
        symbol: "lib/erc404/contracts/ERC404.sol",
        tokenURI: "lib/erc404/contracts/ERC404.sol",
        totalSupply: "lib/erc404/contracts/ERC404.sol",
        transfer: "lib/erc404/contracts/ERC404.sol",
        transferFrom: "lib/erc404/contracts/ERC404.sol",
        units: "lib/erc404/contracts/ERC404.sol",
      },
    },
  },
  314159: {
    Swap: {
      address: "0x7b905856a76a04e9b11da57ac23ed699729a0325",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner_",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "DtToFil",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "success",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "FilToDt",
          inputs: [],
          outputs: [
            {
              name: "sucess",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setErc404",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "fil",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "dog",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {
        owner: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        renounceOwnership: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        transferOwnership: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
      },
    },
    Dogtoken: {
      address: "0x7df25b80f1c0d26b76defcee6399fa159bb8f7d2",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "name_",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol_",
              type: "string",
              internalType: "string",
            },
            {
              name: "decimals_",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "maxTotalSupplyERC721_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "initialOwner_",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "DOMAIN_SEPARATOR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ID_ENCODING_PREFIX",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender_",
              type: "address",
              internalType: "address",
            },
            {
              name: "valueOrId_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc20Approve",
          inputs: [
            {
              name: "spender_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "erc20BalanceOf",
          inputs: [
            {
              name: "owner_",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc20TotalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc20TransferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "erc721Approve",
          inputs: [
            {
              name: "spender_",
              type: "address",
              internalType: "address",
            },
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "erc721BalanceOf",
          inputs: [
            {
              name: "owner_",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc721TotalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc721TransferExempt",
          inputs: [
            {
              name: "target_",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "erc721TransferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getApproved",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getERC721QueueLength",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getERC721TokensInQueue",
          inputs: [
            {
              name: "start_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "count_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isApprovedForAll",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "minted",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nonces",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owned",
          inputs: [
            {
              name: "owner_",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerOf",
          inputs: [
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "erc721Owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "permit",
          inputs: [
            {
              name: "owner_",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deadline_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "v_",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "r_",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "s_",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data_",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setApprovalForAll",
          inputs: [
            {
              name: "operator_",
              type: "address",
              internalType: "address",
            },
            {
              name: "approved_",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setERC721TransferExempt",
          inputs: [
            {
              name: "account_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSelfERC721TransferExempt",
          inputs: [
            {
              name: "state_",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenURI",
          inputs: [
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "value_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from_",
              type: "address",
              internalType: "address",
            },
            {
              name: "to_",
              type: "address",
              internalType: "address",
            },
            {
              name: "valueOrId_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "units",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "updatedtokenURI",
          inputs: [
            {
              name: "id_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "path",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "success",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ApprovalForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyExists",
          inputs: [],
        },
        {
          type: "error",
          name: "DecimalsTooLow",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientAllowance",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidApproval",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidExemption",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidOperator",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidRecipient",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSender",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSigner",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSpender",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidTokenId",
          inputs: [],
        },
        {
          type: "error",
          name: "MintLimitReached",
          inputs: [],
        },
        {
          type: "error",
          name: "NotFound",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnedIndexOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "PermitDeadlineExpired",
          inputs: [],
        },
        {
          type: "error",
          name: "QueueEmpty",
          inputs: [],
        },
        {
          type: "error",
          name: "QueueFull",
          inputs: [],
        },
        {
          type: "error",
          name: "QueueOutOfBounds",
          inputs: [],
        },
        {
          type: "error",
          name: "RecipientIsERC721TransferExempt",
          inputs: [],
        },
        {
          type: "error",
          name: "Unauthorized",
          inputs: [],
        },
        {
          type: "error",
          name: "UnsafeRecipient",
          inputs: [],
        },
      ],
      inheritedFunctions: {
        owner: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        renounceOwnership: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        transferOwnership: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        DOMAIN_SEPARATOR: "lib/erc404/contracts/ERC404.sol",
        ID_ENCODING_PREFIX: "lib/erc404/contracts/ERC404.sol",
        allowance: "lib/erc404/contracts/ERC404.sol",
        approve: "lib/erc404/contracts/ERC404.sol",
        balanceOf: "lib/erc404/contracts/ERC404.sol",
        decimals: "lib/erc404/contracts/ERC404.sol",
        erc20Approve: "lib/erc404/contracts/ERC404.sol",
        erc20BalanceOf: "lib/erc404/contracts/ERC404.sol",
        erc20TotalSupply: "lib/erc404/contracts/ERC404.sol",
        erc20TransferFrom: "lib/erc404/contracts/ERC404.sol",
        erc721Approve: "lib/erc404/contracts/ERC404.sol",
        erc721BalanceOf: "lib/erc404/contracts/ERC404.sol",
        erc721TotalSupply: "lib/erc404/contracts/ERC404.sol",
        erc721TransferExempt: "lib/erc404/contracts/ERC404.sol",
        erc721TransferFrom: "lib/erc404/contracts/ERC404.sol",
        getApproved: "lib/erc404/contracts/ERC404.sol",
        getERC721QueueLength: "lib/erc404/contracts/ERC404.sol",
        getERC721TokensInQueue: "lib/erc404/contracts/ERC404.sol",
        isApprovedForAll: "lib/erc404/contracts/ERC404.sol",
        minted: "lib/erc404/contracts/ERC404.sol",
        name: "lib/erc404/contracts/ERC404.sol",
        nonces: "lib/erc404/contracts/ERC404.sol",
        owned: "lib/erc404/contracts/ERC404.sol",
        ownerOf: "lib/erc404/contracts/ERC404.sol",
        permit: "lib/erc404/contracts/ERC404.sol",
        safeTransferFrom: "lib/erc404/contracts/ERC404.sol",
        setApprovalForAll: "lib/erc404/contracts/ERC404.sol",
        setSelfERC721TransferExempt: "lib/erc404/contracts/ERC404.sol",
        supportsInterface: "lib/erc404/contracts/ERC404.sol",
        symbol: "lib/erc404/contracts/ERC404.sol",
        tokenURI: "lib/erc404/contracts/ERC404.sol",
        totalSupply: "lib/erc404/contracts/ERC404.sol",
        transfer: "lib/erc404/contracts/ERC404.sol",
        transferFrom: "lib/erc404/contracts/ERC404.sol",
        units: "lib/erc404/contracts/ERC404.sol",
      },
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
